### ISSUE TITLE
DNG-CALL Vcf Alt drops sites unexpectedly.

### ISSUE THREAD

**Issue by reedacartwright** [denovogear/denovogear#132]
While solving #110, the testing system is being revamped.  It has been discovered that in the new/renamed `DngCall.Vcf.TrioAlt` test that the following line produces no output even if `-m 0` is set.

```
5   126385929   .   G   X   0   PASS    LL=-74.6814;PMUT=1  AD  29,1    57,0    76,1
```

This suggests that, if `X` is the only ALT, the depth of the reference allele is set to 0.

**Comment by jgarciamesa** [comment]
When there is an X in the alternative allele htslib does not treat it as a variant. It treats it as if there was a '.' in the ALT column. According to samtools mpileup:
In the BCF generated by SAMtools, an non-ref base 'X' represents an base has not been seen from the alignment data. Such a base is necessary to evaluate the probability of missing a non-ref allele due to sampling fluctuation. 
@reedacartwright How should we treat the ALT with just and 'X' allele?

**Comment by jgarciamesa** [comment]
The VCFPileup function checks that the record for the current line of the vcf input file is for an SNP. If it is an SNP then processes the record otherwise skips the current line. As it is implemented on htslib, when the ALT is only 'X' it is not treated as a variant, so there is no output for the following line. 

`5     126385929     .     G     X     0     PASS      LL=-74.6814;PMUT=1     AD     29,1     57,0     76,1`

**Comment by reedacartwright** [comment]
Okay. We need to change the algorithm so that it processes the site even if it is not polymorphic.  We want to skip indels, not sites like this.
