### ISSUE TITLE
dng-dnm assumes DP is zero

### ISSUE THREAD

**Issue by reedacartwright** [denovogear/denovogear#151]
`dng-dnm` measures coverage using the DP format-tag or I16 info-tag. If those are missing from a VCF it will assume that the depth is 0 and not produce output.

We have two options to fix this:
1. Better documentation and error/warning messages
2. Change the behavior such that if DP and I16 are missing the site is not filtered.

Reported by Michael Kessler

**Comment by jgarc111** [comment]
I have already change it so it doesn't stop if there is no DP or I16 information-tag, but I was wondering what information would be interesting to show on the error message beyond "BCF PARSING ERROR - Skipping site".

**Comment by jgarciamesa** [comment]
Testing with different sites as VCF inpdut and looking into the code I have observed that if the site contains the PL format-tag it won't produce an error and will keep filtering the following sites. Otherwise, if the PL format-tag is missing it will throw a BCF parsing error: `BCF PARSING ERROR - Trios!`. If I am not mistaken, I would edit it so when the PL format-tag is not found it throws a more detailed error and also keeps filtering the rest of the sites. @reedacartwright

**Comment by reedacartwright** [comment]
Yes, that sounds reasonable.

**Comment by jgarciamesa** [comment]
This seems to have been fixed on merged pull request #224.
